---
- name: update the machine
  apt:
    update_cache: yes

- name: upgrade the machine
  apt:
    upgrade: full

- name: install some network tools
  apt:
    name: tcptraceroute
  with_items:
  - tcptraceroute
  - jnettop
  - iproute
...
