---
- name: update the machine
  apt:
    update_cache: yes

- name: upgrade the machine
  apt:
    upgrade: full

- name: install some network tools
  apt:
    name: tcptraceroute
  with_items:
  - tcptraceroute
  - jnettop
  - iproute

- name: add boxa1 to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.50.11 boxa1 boxa1.locala.dev"
    state: present
- name: add boxa2 to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.50.12 boxa2 boxa2.locala.dev"
    state: present
- name: add boxa1 to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.60.11 boxb1 boxb1.localb.dev"
    state: present
- name: add boxb2 to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.60.12 boxb2 boxb2.localb.dev"
    state: present
...
