---
- name: set forwarding and masquerading for the internet access for 192.168.50.0/24
  shell: |
    iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
    iptables -A FORWARD -i enp0s3 -o enp0s8 -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -A FORWARD -i enp0s8 -o enp0s3 -j ACCEPT
  args:
    executable: /bin/bash

- name: set forwarding and masquerading for the internet access for 192.168.70.0/24
  shell: |
    iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
    iptables -A FORWARD -i enp0s3 -o enp0s9 -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -A FORWARD -i enp0s9 -o enp0s3 -j ACCEPT
  args:
    executable: /bin/bash
...
